version: "3"

services: 
  web:
    build: .
    image: jdserver/xxd-web
    container_name: xxd-web
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xxd.rule=Host(`xxd.jdtech.dev`)"
      - "traefik.http.routers.xxd.entrypoints=websecure"
      - "traefik.http.routers.xxd.tls=true"

networks:
  proxy:
    external: true